CREATE TABLE [dbo].[Team]
(
  [Id] INT IDENTITY NOT NULL CONSTRAINT [PK_Team] PRIMARY KEY,
  [Name] NVARCHAR(100) NOT NULL,
  [UserAId] INT NOT NULL,
  [UserBId] INT NOT NULL,
  CONSTRAINT [FK_Team_UserA] FOREIGN KEY (UserAId) REFERENCES [User](Id),
  CONSTRAINT [FK_Team_UserB] FOREIGN KEY (UserBId) REFERENCES [User](Id)
)