CREATE TABLE [dbo].[User]
(
  [Id] INT IDENTITY NOT NULL CONSTRAINT [PK_User] PRIMARY KEY,
  [Username] NVARCHAR(50) NOT NULL,
  [Email] NVARCHAR(100) NOT NULL,
  [PasswordHash] NVARCHAR(256) NOT NULL,
  [Role] NVARCHAR(20) NOT NULL CONSTRAINT [DF_Role] DEFAULT 'User',
)